# Generated by Django 6.0.4 on 2026-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_bank_reference_payment_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('card', 'Card')], max_length=10),
        ),
    ]
