# Generated by Django 6.0.4 on 2026-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('bank', 'Bank Transfer'), ('card', 'Card')], max_length=10),
        ),
    ]
