# Generated by Django 6.0.4 on 2026-05-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=10),
        ),
    ]
