# Generated by Django 6.0.4 on 2026-06-02 11:00

from django.db import migrations, models
from django.db.models import Max


def remove_duplicate_emails(apps, schema_editor):
    """Remove duplicate users, keeping only the most recent one for each email."""
    User = apps.get_model('users', 'User')
    
    # Get all emails that have duplicates
    from django.db.models import Count
    duplicate_emails = User.objects.values('email').filter(
        email__isnull=False
    ).annotate(count=Count('id')).filter(count__gt=1)
    
    for dup in duplicate_emails:
        email = dup['email']
        # Get all users with this email, ordered by id descending (keep the latest)
        users_with_email = User.objects.filter(email=email).order_by('-id')
        
        # Keep the first one (most recent) and delete the rest
        users_to_delete = users_with_email[1:]
        for user in users_to_delete:
            user.delete()


def reverse_remove_duplicates(apps, schema_editor):
    """Reverse function - cannot restore deleted users."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_agreed_privacy_user_agreed_terms_user_city_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_emails, reverse_remove_duplicates),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                condition=models.Q(('email__isnull', False)),
                fields=('email',),
                name='unique_email'
            ),
        ),
    ]
