# Generated by Django 6.0.4 on 2026-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_duplicate_emails_and_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
