# Generated by Django 6.0.4 on 2026-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
