# Generated by Django 6.0.4 on 2026-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_notes_order_tracking_number_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_kra_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
