# Generated by Django 6.0.4 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='organization',
            new_name='contact_person',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
