# Generated by Django 6.0.4 on 2026-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Optional response note for the customer.', null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quotation_document',
            field=models.FileField(blank=True, help_text='Upload the quotation document for this customer.', null=True, upload_to='quotes/quotation/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
